# Generated by Django 4.0.6 on 2022-07-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_user_readme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_readme',
            field=models.TextField(default=' ', null=True),
        ),
    ]
